name: Buycraft
main: net.buycraft.Plugin
version: 4.8
author: Buycraft Development Team
website: https://buycraft.net
commands:
   buy:
      usage: Type /buycraft for assistance
   ec:
      usage: /<command>
   buycraft:
      usage: /<command> <reload/forcecheck/secret>