name: Buycraft
main: net.buycraft.Plugin
version: 5.2
author: Tebex Technologies Ltd
website: http://buycraft.net
commands:
   buy:
      usage: Type /buycraft for assistance
   ec:
      usage: /<command>
   buycraft:
      usage: /<command> <reload/forcecheck/secret>